# Generated by Django 5.0.3 on 2024-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_subscribers_verified_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribers",
            name="valid_user",
            field=models.BooleanField(default=False),
        ),
    ]
